Controllers/BudgetController.cs
using gestion_budget.Models;
using System.Security.Claims;
using gestion_budget.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Packaging.Signing;
using System;

namespace gestion_budget.Controllers
{
    [Authorize]
    public class BudgetController : Controller
    {
        private readonly BudgetService _budgetService;

        public BudgetController()
        {
            var connectionString = "Server=DESKTOP-7A266J8;Database=BudgetManagement;Trusted_Connection=True;Encrypt=True;TrustServerCertificate=True";
            _budgetService = new BudgetService(connectionString);
        }
        public IActionResult List()
        {
            var budgets = _budgetService.GetBudgets();
            return View(budgets);
        }

        public IActionResult Add()
        {
            var categories = _budgetService.GetCategories();
            ViewBag.Categories = categories ?? new List<Category>();
            ViewBag.UserId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            return View();
        }

        [HttpPost]
        public IActionResult Add(int CategoryId, int UserId, decimal BudgetAmount, DateTime StartDate, DateTime EndDate)
        {
            try
            {
                var budget = new Budget
                {
                    CategoryId = CategoryId,
                    UserId = UserId,
                    BudgetAmount = BudgetAmount,
                    StartDate = StartDate,
                    EndDate = EndDate
                };

                _budgetService.AddBudget(budget);
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                ModelState.AddModelError("", "Une erreur s'est produite lors de l'ajout du budget.");
                return View(new Budget
                {
                    CategoryId = CategoryId,
                    UserId = UserId,
                    BudgetAmount = BudgetAmount,
                    StartDate = StartDate,
                    EndDate = EndDate
                });
            }
        }

        [HttpGet("Budget/GetById/{id}")]
        public IActionResult GetById(int id)
        {
            var budget = _budgetService.GetBudgets().FirstOrDefault(b => b.BudgetId == id);
            if (budget == null)
            {
                return NotFound();
            }

            return Json(budget);
        }

        [HttpGet("Budget/Edit/{id}")]
        public IActionResult Edit(int id)
        {
            var budget = _budgetService.GetBudgets().FirstOrDefault(b => b.BudgetId == id);
            if (budget == null)
            {
                return NotFound();
            }
            var categories = _budgetService.GetCategories();
            ViewBag.Categories = categories;
            return View(budget);
        }

        [HttpPut("Budget/Update")]
        public IActionResult Update([FromBody] Budget budget)
        {
            try
            {
                _budgetService.UpdateBudget(budget);
                return Ok(new { success = true });
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                return BadRequest(new { message = "Une erreur s'est produite lors de la modification du budget." });
            }
        }

        [HttpPost("Budget/Delete/{id}")]
        public IActionResult Delete(int id)
        {
            try
            {
                _budgetService.DeleteBudget(id);
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                ModelState.AddModelError("", "Une erreur s'est produite lors de la suppression du budget.");
                return RedirectToAction("List");
            }
        }

        [HttpGet("Transaction/TransBudget/{CategoryId}/{StartDate}/{EndDate}/{BudgetAmount}")]
        public IActionResult ViewTransactionBudget(int CategoryId, long StartDate, long EndDate, decimal BudgetAmount)
        {
            DateTimeOffset start = DateTimeOffset.FromUnixTimeMilliseconds(StartDate);
            DateTimeOffset end = DateTimeOffset.FromUnixTimeMilliseconds(EndDate);

            DateTime dateTimeStart = start.UtcDateTime;
            DateTime dateTimeEnd = end.UtcDateTime;

            try
            {
                var (transactions, totalAmount) = _budgetService.ViewTransactionBudget(CategoryId, dateTimeStart, dateTimeEnd);

                if (transactions == null || !transactions.Any())
                {
                    ViewBag.TotalAmount = 0;
                    ViewBag.BudgetAmount = BudgetAmount;
                    return View("transBudget", new List<Transaction>());
                }

                ViewBag.TotalAmount = totalAmount;
                ViewBag.BudgetAmount = BudgetAmount;
                return View("transBudget", transactions);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                return StatusCode(500, "Une erreur s'est produite.");
            }
        }

    }
}

Controllers/TransactionController.cs
using System.Security.Claims;
using System.Text;
using gestion_budget.DAL;
using gestion_budget.Models;
using gestion_budget.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;

namespace gestion_budget.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        private readonly AppDbContext _context;
        private readonly TransactionService _transactionService;
        public TransactionController(AppDbContext context)
        {
            var connectionString = "Server=DESKTOP-7A266J8;Database=BudgetManagement;Trusted_Connection=True;Encrypt=True;TrustServerCertificate=True";
            _transactionService = new TransactionService(connectionString);
            _context = context;
        }

        public IActionResult List(int page = 1, int pageSize = 10, int? categoryId = null, bool? isIncome = null, DateTime? startDate = null, DateTime? endDate = null, decimal? minAmount = null, decimal? maxAmount = null)
        {
            var transactions = _transactionService.GetTransactions(page, pageSize, categoryId, isIncome, startDate, endDate, minAmount, maxAmount);
            var totalTransactions = _transactionService.GetTotalTransactionsCount();
            var subcategories = _transactionService.GetSubCat();
            ViewBag.subcategories = subcategories ?? new List<Category>();
            ViewBag.TotalPages = (int)Math.Ceiling((double)totalTransactions / pageSize);
            ViewBag.CurrentPage = page;
            return View(transactions);
        }
        public IActionResult Add()
        {
            var categories = _transactionService.GetCategories();
            ViewBag.Categories = categories ?? new List<Category>();
            ViewBag.UserId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            return View();
        }

        [HttpPost]
        public IActionResult Add(int CategoryId, int? SubCategoryId, int UserId, decimal Amount, DateTime TransactionDate, string Note)
        {
            try
            {
                var transaction = new Transaction
                {
                    CategoryId = SubCategoryId ?? CategoryId,
                    UserId = UserId,
                    Amount = Amount,
                    TransactionDate = TransactionDate,
                    Note = Note
                };

                _transactionService.AddTransaction(transaction);
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                ModelState.AddModelError("", "Une erreur s'est produite lors de l'insertion de la transaction.");
                return View(new Transaction
                {
                    CategoryId = SubCategoryId ?? CategoryId,
                    UserId = UserId,
                    Amount = Amount,
                    TransactionDate = TransactionDate,
                    Note = Note
                });
            }
        }


        [HttpGet("Transaction/GetById/{id}")]
        public IActionResult GetById(int id)
        {
            var transaction = _transactionService.GetTransactionById(id);
            if (transaction == null)
            {
                return NotFound();
            }

            return Json(transaction);
        }

        [HttpGet("Transaction/Edit/{id}")]
        public IActionResult Edit(int id)
        {
            var transaction = _transactionService.GetTransactionById(id);
            if (transaction == null)
            {
                return NotFound();
            }

            var categories = _transactionService.GetSubCat();
            ViewBag.Categories = categories ?? new List<Category>();
            return View(transaction);
        }

        [HttpPut("Transaction/Update")]
        public IActionResult Update([FromBody] Transaction transaction)
        {
            try
            {
                _transactionService.UpdateTransaction(transaction);
                return Ok(new { success = true });
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                return BadRequest(new { message = "Une erreur s'est produite lors de la modification de la transaction." });
            }
        }

        [HttpPost("Transaction/Delete/{id}")]
        public IActionResult Delete(int id)
        {
            try
            {
                _transactionService.DeleteTransaction(id);
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                ModelState.AddModelError("", "Une erreur s'est produite lors de la suppression de la transaction.");
                return RedirectToAction("List");
            }
        }

        [HttpGet("Transaction/GetSubCategories/{id}")]
        public IActionResult GetSubCategories(int id)
        {
            var subCategories = _transactionService.GetSubCatByIdCat(id);
            return Json(subCategories);
        }

        public IActionResult Export(int? categoryId = null, bool? isIncome = null, DateTime? startDate = null, DateTime? endDate = null, decimal? minAmount = null, decimal? maxAmount = null)
        {
            var transactions = _transactionService.GetTransactions(1, int.MaxValue, categoryId, isIncome, startDate, endDate, minAmount, maxAmount);

            var csv = new StringBuilder();
            csv.AppendLine("TransactionId,Category,Type,Amount,Date,Note");

            foreach (var transaction in transactions)
            {
                var type = transaction.Category.IsIncome ? "Revenu" : "Dépense";
                var amount = transaction.Category.IsIncome ? $"+{transaction.Amount:N0}" : $"-{transaction.Amount:N0}";
                csv.AppendLine($"{transaction.TransactionId},{transaction.Category.Name},{type},{amount},{transaction.TransactionDate:dd-MM-yyyy HH:mm},{transaction.Note}");
            }

            var fileName = "transactions_export.csv";
            return File(Encoding.UTF8.GetBytes(csv.ToString()), "text/csv", fileName);
        }

        public IActionResult ExportExcel(int? categoryId = null, bool? isIncome = null, DateTime? startDate = null, DateTime? endDate = null, decimal? minAmount = null, decimal? maxAmount = null)
        {
            var transactions = _transactionService.GetTransactions(1, int.MaxValue, categoryId, isIncome, startDate, endDate, minAmount, maxAmount);

            using (var package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add("Transactions");
                worksheet.Cells[1, 1].Value = "TransactionId";
                worksheet.Cells[1, 2].Value = "Category";
                worksheet.Cells[1, 3].Value = "Type";
                worksheet.Cells[1, 4].Value = "Amount";
                worksheet.Cells[1, 5].Value = "Date";
                worksheet.Cells[1, 6].Value = "Note";

                int row = 2;
                foreach (var transaction in transactions)
                {
                    var type = transaction.Category.IsIncome ? "Revenu" : "Dépense";
                    var amount = transaction.Category.IsIncome ? $"+{transaction.Amount:N0}" : $"-{transaction.Amount:N0}";
                    worksheet.Cells[row, 1].Value = transaction.TransactionId;
                    worksheet.Cells[row, 2].Value = transaction.Category.Name;
                    worksheet.Cells[row, 3].Value = type;
                    worksheet.Cells[row, 4].Value = amount;
                    worksheet.Cells[row, 5].Value = transaction.TransactionDate.ToString("dd-MM-yyyy HH:mm");
                    worksheet.Cells[row, 6].Value = transaction.Note;
                    row++;
                }

                var fileContents = package.GetAsByteArray();
                var fileName = "transactions_export.xlsx";
                return File(fileContents, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
            }
        }
        [HttpPost]
        public IActionResult UploadCsv(IFormFile csvFile)
        {
            if (csvFile == null || csvFile.Length == 0)
            {
                return Json(new { success = false, message = "Veuillez sélectionner un fichier CSV valide." });
            }

            var uploadedData = new List<string[]>();
            try
            {
                using (var reader = new StreamReader(csvFile.OpenReadStream()))
                {
                    var lines = reader.ReadToEnd().Split('\n', StringSplitOptions.RemoveEmptyEntries);

                    foreach (var line in lines.Skip(1)) // Ignorer l'en-tête
                    {
                        var values = line.Split(',', StringSplitOptions.TrimEntries);
                        uploadedData.Add(values);
                    }
                }

                return Json(new
                {
                    success = true,
                    message = $"{uploadedData.Count} lignes extraites avec succès.",
                    rows = uploadedData
                });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = $"Erreur lors de l'extraction : {ex.Message}" });
            }
        }

        [HttpPost]
        public JsonResult InsertData([FromBody] DataPayload payload)
        {
            if (payload == null || payload.Data == null || payload.Data.Count == 0)
            {
                return Json(new { success = false, message = "Aucune donnée à traiter." });
            }

            var transactions = new List<Transaction>();
            foreach (var row in payload.Data)
            {
                var category = _context.Categories
                    .FirstOrDefault(c => c.Name == row[0].Trim());

Pages/Shared/_Layout.cshtml
@using gestion_budget.Services
@inject UserService UserService

@{
    var userName = UserService.GetUserName();
    var roleId = UserService.GetRoleId();
    var userId = UserService.GetAuthenticatedUserId();
    decimal? userBalance = null;

    if (userId.HasValue)
    {
        userBalance = await UserService.GetUserBalanceByIdAsync(userId.Value);
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gestion budget</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/gestion_budget.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/js/site.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Gestion budget</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>

                        @if (roleId == 1)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/Back-Office/Categories/lists">Categories</a>
                            </li>
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-page="/Back-Office/Setting/index">Plafonds</a>
                            </li>
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-page="/Back-Office/Alerts/lists">Alerts</a>
                            </li>
                        }
                        @if (roleId == 2)
                        {
                            <li>
                                <a class="nav-link text-dark" asp-controller="Transaction" asp-action="List">Transaction</a>
                            </li>
                            <li>
                                <a class="nav-link text-dark" asp-controller="Budget" asp-action="List">Budget</a>
                            </li>
                        }
                    </ul>

                    @if (roleId == 2)
                    {
                        @if (userBalance.HasValue)
                        {
                            <span class="nav-link text-dark">Solde: @userBalance.Value.ToString("N0") Ar</span>
                        }
                        else
                        {
                            <span class="nav-link text-dark">Solde: N/A</span>
                        }
                    }
                    &nbsp;
                    <form method="get" asp-page="/Back-Office/Account/Logout" style="display:inline;">
                        <button type="submit" class="btn btn-danger">Déconnexion</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Gestion budget
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>